# 変更されたファイルに基づいてPRにラベルを付与

api:
  - changed-files:
    - any-glob-to-any-file: 'apps/api/**/*'

types:
  - changed-files:
    - any-glob-to-any-file: 'packages/types/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - '**/*.yml'
      - '**/*.yaml'

database:
  - changed-files:
    - any-glob-to-any-file:
      - 'apps/api/src/db/**/*'
      - '**/migrations/**/*'
      - '**/schema.ts'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/pnpm-lock.yaml'
      - '**/yarn.lock'
